version: '3.8'
services:
  proxies:
    build: .
    container_name: proxies
    networks:
      proxy_net:
        ipv4_address: 188.34.153.224
    volumes:
      - .:.
    deploy:
      resources:
        limits:
          memory: 1024m
    restart: always
    environment:
      - SERVER_IP: 66.220.18.42
      - CLIENT_IP: 188.34.153.224
      - PROXY_LOGIN: humble
      - PROXY_PASS: k3u22cab
      - PROXY_START_PORT: 10000
      - PROXY_COUNT: 10000
    sysctls:
      - net.ipv6.conf.all.proxy_ndp: 1
      - net.ipv6.conf.default.forwarding: 1
      - net.ipv6.conf.all.forwarding: 1
      - net.ipv6.ip_nonlocal_bind: 1
      - net.ipv6.route.max_size: 409600
      - net.ipv4.tcp_max_syn_backlog: 4096
      - net.ipv6.neigh.default.gc_thresh3: 102400
      - kernel.threads-max: 1200000
      - kernel.max_map_count: 6000000
      - vm.max_map_count: 6000000
      - kernel.pid_max: 2000000
    ulimits:
